#!/bin/bash
# Quick setup script for Nico LAN deployment

set -e

echo "========================================="
echo "Nico LAN Deployment Setup"
echo "========================================="
echo ""

# Function to check if command exists
command_exists() {
    command -v "$1" >/dev/null 2>&1
}

# Function to prompt for input with default
prompt_with_default() {
    local prompt="$1"
    local default="$2"
    local result
    
    read -p "$prompt [$default]: " result
    echo "${result:-$default}"
}

# Detect setup type
echo "What would you like to set up?"
echo "1) Nico Client (writing PC)"
echo "2) Embedding Server (dedicated PC with optional GPU)"
echo "3) Both on this machine"
echo ""
read -p "Choice [1]: " SETUP_TYPE
SETUP_TYPE=${SETUP_TYPE:-1}

# ============================================================================
# Nico Client Setup
# ============================================================================
if [ "$SETUP_TYPE" = "1" ] || [ "$SETUP_TYPE" = "3" ]; then
    echo ""
    echo "=== Nico Client Configuration ==="
    echo ""
    
    # Check if .env exists
    if [ -f .env ]; then
        read -p ".env file already exists. Overwrite? (y/N): " OVERWRITE
        if [ "$OVERWRITE" != "y" ] && [ "$OVERWRITE" != "Y" ]; then
            echo "Keeping existing .env"
            exit 0
        fi
    fi
    
    # Prompt for configuration
    echo "Enter your configuration details:"
    echo ""
    
    DB_HOST=$(prompt_with_default "PostgreSQL host (IP or hostname)" "localhost")
    DB_PORT=$(prompt_with_default "PostgreSQL port" "5432")
    DB_NAME=$(prompt_with_default "Database name" "nico")
    DB_USER=$(prompt_with_default "Database user" "nico_user")
    read -sp "Database password: " DB_PASS
    echo ""
    
    echo ""
    read -p "Use embedding service? (Y/n): " USE_EMBEDDING
    USE_EMBEDDING=${USE_EMBEDDING:-Y}
    
    if [ "$USE_EMBEDDING" = "y" ] || [ "$USE_EMBEDDING" = "Y" ]; then
        EMBED_HOST=$(prompt_with_default "Embedding service host (IP or hostname)" "localhost")
        EMBED_PORT=$(prompt_with_default "Embedding service port" "8000")
        EMBEDDING_URL="http://${EMBED_HOST}:${EMBED_PORT}"
    else
        EMBEDDING_URL=""
    fi
    
    echo ""
    OLLAMA_HOST=$(prompt_with_default "Ollama host (IP or hostname)" "localhost")
    OLLAMA_PORT=$(prompt_with_default "Ollama port" "11434")
    OLLAMA_URL="http://${OLLAMA_HOST}:${OLLAMA_PORT}"
    
    # Create .env file
    cat > .env << EOF
# Nico Configuration
# Generated by setup script on $(date)

# Database
DATABASE_URL=postgresql://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME}

# Embedding Service
EMBEDDING_SERVICE_URL=${EMBEDDING_URL}
EMBEDDING_FALLBACK_LOCAL=true

# Ollama
OLLAMA_BASE_URL=${OLLAMA_URL}

# Optional: Add your API keys here
# OPENAI_API_KEY=sk-...
# ANTHROPIC_API_KEY=sk-ant-...
# GOOGLE_API_KEY=AIza...

# Application
DEBUG=false
EOF
    
    echo ""
    echo "✓ .env file created"
    
    # Check if database is reachable
    echo ""
    echo "Testing PostgreSQL connection..."
    if command_exists psql; then
        if PGPASSWORD="${DB_PASS}" psql -h "${DB_HOST}" -p "${DB_PORT}" -U "${DB_USER}" -d "${DB_NAME}" -c "SELECT 1" >/dev/null 2>&1; then
            echo "✓ PostgreSQL connection successful"
        else
            echo "⚠ Could not connect to PostgreSQL. Please check your settings."
        fi
    else
        echo "⚠ psql not installed, skipping connection test"
    fi
    
    # Run migrations
    echo ""
    read -p "Run database migrations now? (Y/n): " RUN_MIGRATIONS
    RUN_MIGRATIONS=${RUN_MIGRATIONS:-Y}
    
    if [ "$RUN_MIGRATIONS" = "y" ] || [ "$RUN_MIGRATIONS" = "Y" ]; then
        if command_exists alembic; then
            echo "Running migrations..."
            alembic upgrade head
            echo "✓ Migrations complete"
        else
            echo "⚠ alembic not installed. Run: pip install alembic"
        fi
    fi
    
    echo ""
    echo "========================================="
    echo "✓ Nico Client Setup Complete"
    echo "========================================="
    echo ""
    echo "To start Nico:"
    echo "  python -m nico"
    echo ""
fi

# ============================================================================
# Embedding Server Setup
# ============================================================================
if [ "$SETUP_TYPE" = "2" ] || [ "$SETUP_TYPE" = "3" ]; then
    echo ""
    echo "=== Embedding Server Setup ==="
    echo ""
    
    # Check Python version
    PYTHON_VERSION=$(python3 --version 2>&1 | awk '{print $2}')
    echo "Python version: $PYTHON_VERSION"
    
    # Check for GPU
    if command_exists nvidia-smi; then
        echo ""
        echo "NVIDIA GPU detected:"
        nvidia-smi --query-gpu=name,memory.total --format=csv,noheader
        USE_GPU="Y"
    else
        echo "No NVIDIA GPU detected (will use CPU)"
        USE_GPU="N"
    fi
    
    echo ""
    read -p "Install embedding server dependencies? (Y/n): " INSTALL_DEPS
    INSTALL_DEPS=${INSTALL_DEPS:-Y}
    
    if [ "$INSTALL_DEPS" = "y" ] || [ "$INSTALL_DEPS" = "Y" ]; then
        echo "Installing dependencies..."
        
        # Create virtual environment if not exists
        if [ ! -d "venv" ]; then
            python3 -m venv venv
            echo "✓ Virtual environment created"
        fi
        
        source venv/bin/activate
        
        # Install packages
        pip install --upgrade pip
        
        if [ "$USE_GPU" = "Y" ]; then
            echo "Installing with CUDA support..."
            pip install torch torchvision --index-url https://download.pytorch.org/whl/cu121
        else
            echo "Installing CPU-only version..."
            pip install torch torchvision
        fi
        
        pip install fastapi uvicorn[standard] sentence-transformers pillow
        
        echo "✓ Dependencies installed"
        
        # Test installation
        echo ""
        echo "Testing installation..."
        python3 -c "import torch; print(f'PyTorch: {torch.__version__}'); print(f'CUDA available: {torch.cuda.is_available()}')"
        
        echo ""
        echo "Downloading embedding model (this may take a few minutes)..."
        python3 -c "from sentence_transformers import SentenceTransformer; SentenceTransformer('nomic-ai/nomic-embed-text-v1.5')"
        echo "✓ Model downloaded"
    fi
    
    # Get network interface
    echo ""
    IP_ADDR=$(hostname -I | awk '{print $1}')
    echo "Detected IP address: $IP_ADDR"
    
    HOST=$(prompt_with_default "Host to bind to (0.0.0.0 for all interfaces)" "0.0.0.0")
    PORT=$(prompt_with_default "Port to bind to" "8000")
    
    # Create systemd service
    echo ""
    read -p "Create systemd service for autostart? (y/N): " CREATE_SERVICE
    
    if [ "$CREATE_SERVICE" = "y" ] || [ "$CREATE_SERVICE" = "Y" ]; then
        SERVICE_FILE="/etc/systemd/system/nico-embedding.service"
        WORK_DIR=$(pwd)
        USER=$(whoami)
        
        sudo tee "$SERVICE_FILE" > /dev/null << EOF
[Unit]
Description=Nico Embedding Service
After=network.target

[Service]
Type=simple
User=$USER
WorkingDirectory=$WORK_DIR
Environment="PATH=$WORK_DIR/venv/bin"
ExecStart=$WORK_DIR/venv/bin/uvicorn embedding_server:app --host $HOST --port $PORT --workers 4
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
EOF
        
        sudo systemctl daemon-reload
        sudo systemctl enable nico-embedding
        
        echo "✓ Systemd service created"
        echo ""
        read -p "Start service now? (Y/n): " START_NOW
        START_NOW=${START_NOW:-Y}
        
        if [ "$START_NOW" = "y" ] || [ "$START_NOW" = "Y" ]; then
            sudo systemctl start nico-embedding
            sleep 2
            sudo systemctl status nico-embedding
        fi
    else
        echo ""
        echo "To start the embedding server manually:"
        echo "  source venv/bin/activate"
        echo "  python embedding_server.py --host $HOST --port $PORT"
        echo ""
        echo "Or with uvicorn (production):"
        echo "  uvicorn embedding_server:app --host $HOST --port $PORT --workers 4"
    fi
    
    echo ""
    echo "========================================="
    echo "✓ Embedding Server Setup Complete"
    echo "========================================="
    echo ""
    echo "Service will be available at:"
    echo "  http://$IP_ADDR:$PORT"
    echo ""
    echo "Test with:"
    echo "  curl http://$IP_ADDR:$PORT/health"
    echo ""
fi

echo ""
echo "Setup complete! See docs/LAN_DEPLOYMENT.md for more details."
