"""add_character_image_prompt_and_embedding

Revision ID: 64fca3a3a896
Revises: b490d1542a01
Create Date: 2026-01-21 19:58:16.749350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '64fca3a3a896'
down_revision: Union[str, Sequence[str], None] = 'b490d1542a01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('image_prompt', sa.Text(), nullable=True))
    op.add_column('characters', sa.Column('image_embedding', Vector(768), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'image_embedding')
    op.drop_column('characters', 'image_prompt')
    # ### end Alembic commands ###
