"""add_embedding_vectors_to_entities

Add vector embedding columns to Scene, Character, Location, Event, and Media models
for semantic search and similarity analysis. Embeddings are 768-dimensional vectors
from nomic-embed-text model.

Context awareness note: Embeddings enable semantic search but should be used carefully
with LLM context. While models may support large contexts (1M+ tokens), coherence
degrades around 16k tokens - likely related to human cognitive scope patterns in
training data. Use embeddings to retrieve relevant context, not to stuff everything.

Revision ID: aea9f4624826
Revises: 55ce2aa9315c
Create Date: 2026-01-25 14:45:11.665942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = 'aea9f4624826'
down_revision: Union[str, Sequence[str], None] = '55ce2aa9315c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('text_embedding', Vector(768), nullable=True))
    op.add_column('events', sa.Column('embedding', Vector(768), nullable=True))
    op.add_column('locations', sa.Column('embedding', Vector(768), nullable=True))
    op.add_column('media', sa.Column('embedding', Vector(768), nullable=True))
    op.add_column('scenes', sa.Column('scene_embedding', Vector(768), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenes', 'scene_embedding')
    op.drop_column('media', 'embedding')
    op.drop_column('locations', 'embedding')
    op.drop_column('events', 'embedding')
    op.drop_column('characters', 'text_embedding')
    # ### end Alembic commands ###
